mybatis:
    type-aliases-package: com.example.boot.module
    mapper-locations: classpath*:xmlmap/**/*Mapper.xml

mapper:
#    mappers:
#        - com.example.boot.module
    not-empty: false
    identity: MYSQL

spring:
    datasource:
        url: jdbc:mysql://localhost:3308/db_pms?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
